### ISSUE TITLE
CLR function

### ISSUE THREAD

**Issue by aakornyeyev** [atheken/SQLExtensions#1]
Having troubles making a CLR function of it...

**Comment by atheken** [comment]
I haven't actually used SQL Server for anything in several years, so I may not be able to help much, but I can try. 

Have you followed the instructions as outlined [here](https://github.com/atheken/SQLExtensions#installation)?

What error(s) are you running in to?

**Comment by aakornyeyev** [comment]
Thank you for your response. Appreciated it very much. I actually got it working the way I want. Thanks!

**Comment by atheken** [comment]
No problem, I'm glad you're able to get some use out of these!
